version: "3.9"

services:
  db:
    image: postgres:17
    container_name: kc-pg
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - kc-net

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.3
    container_name: keycloak
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_DB_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
    volumes:
      - kc-data:/opt/keycloak/data
    networks:
      - kc-net

volumes:
  pg-data:
  kc-data:

networks:
  kc-net:
